apiVersion: v1
kind: Service
metadata:
  name: eureka-micro-svc 
  labels:
    service: eureka-micro-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
  selector:
    app: eureka-micro-svc
